### PR TITLE
Removed git references from the gemspec

### PR DESCRIPTION
**Pull request by marothstein**
Also bumped version, added references to Final, and pulled the reference to binary files from the gemspec.

### CODE REVIEW

**Comment by marothstein** [comment]
@arfrank, @arfrank, @arfrank

**Comment by marothstein** [comment]
Also, @Final/team-evan

**Comment by EvanSimpson** [comment]
:+1:

**Comment by marothstein** [comment]
YOU ARE THE BEST

**Comment by marothstein** [comment]
too excited...

**Pull request merged**
